'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RPGXplorer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property a() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("a", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_down_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_up_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Buckler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buckler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;q0am3cMf0hzeNYBPRMT/BTzgULPdRSKw2dwlkTHjYOCx/DmaduAfIW7PUFRLRnBr7QCviOXoB9JOutka+aKVZZ7zuBEGy6O+177+60kuCwtpGnPN07xms+hCtIhQtvCpGx8gM0gN8n975MVFMXrhfkyFznMxr0bo3IQ+WPYl/bk=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        '''</summary>
        Friend ReadOnly Property c() As String
            Get
                Return ResourceManager.GetString("c", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property CharacterHumanMale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CharacterHumanMale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RPGXplorer.
        '''</summary>
        Friend ReadOnly Property d() As String
            Get
                Return ResourceManager.GetString("d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://194.247.87.86/LicenseServer/activator.asmx.
        '''</summary>
        Friend ReadOnly Property DefaultHost() As String
            Get
                Return ResourceManager.GetString("DefaultHost", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property document_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property form_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property funnel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("funnel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property goldbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goldbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property goldbars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goldbars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moneybag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moneybag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Offhand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Offhand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Primary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property row_add_after() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("row_add_after", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property row_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("row_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shield_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoppingbasket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoppingbasket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoppingbasket_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoppingbasket_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ViewModeDetails() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewModeDetails", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ViewModeLargeIcons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewModeLargeIcons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
